---
- name: Install Kicad PPA
  become: true
  apt_repository:
    repo: ppa:kicad/kicad-6.0-releases
    update_cache: yes

- name: Install Kicad 6
  become: true
  apt:
    pkg:
      - kicad
      - kicad-libraries
    state: present
